### ISSUE TITLE
code review feedback

### ISSUE THREAD

**Issue by SoundGoddess** [SoundGoddess/OpenSolitaire#16]
@craftworkgames regarding
https://github.com/craftworkgames/MonoGame.Extended/issues/203#issuecomment-222084625

I'm all for having code be as simplified as possible.  When I originally learned C# back in early 2003, stuff like lists didn't even exist.  Given that I haven't really used it since mid-2005, I only learned about lists when I started on the solitaire project.  I have used VB.NET more recently, up til VS2013.  But once I started playing with VS2015 and MonoGame, C# just seemed to click with me better so I decided to use that instead and probably won't bother using VB.NET for stuff anymore.  The example I saw online showed me that the proper way to order the list was with the foreach loop and yield returns, nice that this is simplified even more so I will update my code with that.

Resharper probably would work ok if I spent enough time fiddling around with the settings.  But out of the box, it makes my sata3 SSD feel like I'm using a fragmented 5400 rpm HDD.  My computer is a Phenom II x4 3.4ghz with 12gb ram, so it shouldn't be killing my performance to that degree.  I'd spend time figuring it out, but it's expensive, and JetBrains wants 3 mos worth of commits to give you a free open source project license.  So, I'll revisit it in another month.

**Comment by SoundGoddess** [comment]
Actually I decided to take another look at Resharper.  It seems like it was conflicting with another extension, once I disabled all the other extensions I wasn't using it seems like it is working ok now.

**Comment by SoundGoddess** [comment]
@craftworkgames so good news and bad news.

Good news is I finally got a working, bug-free build of my game:
http://metasmug.com/i/OpenSolitaire.Classic.0.9.Windows.zip

Bad news is that something got royally f'd up with my repo so my commit didn't merge properly and then github overwrote my local source code with broken merged code that is halfway between yesterday's broken code and today's bug-free code.  All I have to roll back to is yesterday's even more broken source code so I'm feeling pretty frustrated.  I just have to get away from the computer for a while to recharge my batteries so I can figure out wtf went wrong so it doesn't happen again.

**Comment by craftworkgames** [comment]
> Bad news is that something got royally f'd up with my repo so my commit didn't merge properly

Well that sux. I hope you got it sorted out. I've had stuff like that happen once or twice and it's never fun. The silver lining is that the second cut of your code usually turns out better.

**Comment by SoundGoddess** [comment]
Yeah I did get it situated, have you had a chance to play with my bug-free release yet?  Maybe it's bold to claim it to be bug-free, but I haven't been able to break the game since I got all OCD with the debugging.

**Comment by craftworkgames** [comment]
> have you had a chance to play with my bug-free release yet?

I just downloaded it a few moments ago and had a real quick play. I didn't exactly push it to it's limits though.

Overall, I think it's quite polished and you should be very proud of completing a game from start to finish. Most people don't do that on their first try. There's always room for improvement of course, adding a little "juice" to the animations, etc.

I guess the next question is what you plan to do with it now?  It's probably worth writing a post-mortem style blog post about it. Maybe there's some other MonoGame dev's that would appreciate taking a look at the code and learning from your experience.

**Comment by SoundGoddess** [comment]
Well, atm I'm trying to figure out why Mac is refusing to set the icon.  I am also trying to figure out how to upload to Ubuntu software center.  Then I'm going to start working on version 1.0, adding the sound effects, score, and undo button.  Also planning to do some tutorials on the card engine on my Ruge site.  Maybe I can write that up as post-mortem style ;) 

I do have some other ideas in mind.  Namely I plan to create some multi-player card games like hearts, gin rummy, go fish, etc.  Since I was able to build a URL shortener from scratch that had 30,000 active users, I'm confident that I can figure out how to do a multi-player card game.  

Also I am wanting to make a Stardew Valley/Link To The Past/Don't Starve style 2.5d RPG engine.
